# Changes here will be overwritten by Copier
AnswerStrategy: recommended
Authors: SCiarella <simoneciarella@gmail.com>
CodeOfConductContact: simoneciarella@gmail.com
ConfigIndentation: 2
JuliaIndentation: 4
JuliaMinVersion: '1.10'
License: MIT
LicenseCopyrightHolders: SCiarella
MarkdownIndentation: 2
PackageName: ConvolutionalNeuralOperators
PackageOwner: DEEPDIP-project
PackageUUID: d769ba41-1544-53e8-a779-241a28c31cef
_commit: v0.14.0
_src_path: https://github.com/JuliaBesties/BestieTemplate.jl
